#!/bin/sh
# Writes run.sh with absolute paths, because Herdr runs plugin commands as a
# bare argv with no shell expansion and an unreliable PATH.
set -e
dir=$(cd "$(dirname "$0")" && pwd)

find_bin() {
  command -v "$1" 2>/dev/null && return 0
  for candidate in "$HOME/.bun/bin/$1" "$HOME/.local/bin/$1" "/opt/homebrew/bin/$1" "/usr/local/bin/$1"; do
    [ -x "$candidate" ] && printf '%s\n' "$candidate" && return 0
  done
  return 1
}

BUN=$(find_bin bun) || {
  echo "bun not found. Install it from https://bun.sh, then run: sh build.sh"
  exit 1
}

# The installer upgrades an existing CLI in place, so run it every time.
CREATEOS_INSTALL_URL="${CREATEOS_INSTALL_URL:-https://raw.githubusercontent.com/NodeOps-app/createos-cli/main/install.sh}"
if command -v curl >/dev/null 2>&1; then
  echo "Installing or upgrading the createos CLI..."
  # Download first, then run. `curl ... | sh -` hides a failed download: sh
  # reads empty input and exits 0, so a network error looks like a success.
  installer=$(mktemp) || installer=/tmp/createos-install.$$.sh
  if curl -sfL "$CREATEOS_INSTALL_URL" -o "$installer" && [ -s "$installer" ]; then
    sh "$installer" || echo "createos installer failed; falling back to any CLI already present."
  else
    echo "Could not download $CREATEOS_INSTALL_URL; falling back to any CLI already present."
  fi
  rm -f "$installer"
else
  echo "curl not found; skipping the createos install and using any CLI already present."
fi

COS=$(find_bin createos) || {
  echo "createos CLI not found after install. Install it by hand, then run: sh build.sh"
  echo "  curl -sfL $CREATEOS_INSTALL_URL | sh -"
  exit 1
}

cat > "$dir/run.sh" <<EOF
#!/bin/sh
# Generated by build.sh. Do not edit.
CREATEOS_BIN="$COS"
export CREATEOS_BIN
exec "$BUN" "$dir/src/main.ts" "\$@"
EOF
chmod +x "$dir/run.sh"
echo "run.sh written: bun=$BUN createos=$COS"
